employee and student updated to user table
swapiis/SchoolERP pull request #18
Opened 2016-09-24 11:10 UTC by DhanshreeK

2016-09-30 16:34 UTC, swapiis commented on app/controllers/home_controller.rb
> +  prepend_before_filter :require_no_authentication, only: [:cancel ]
What does this change do?

2016-09-30 16:38 UTC, swapiis commented on app/controllers/users_controller.rb
> +    @user = create_user_account(user_params)
where have you defined this method?

2016-09-30 16:39 UTC, swapiis commented on app/controllers/users_controller.rb
> +    @student = User.where(role: 'Student').take
It seems like the previous code was better as here we are getting a `student` only.

2016-09-30 16:42 UTC, swapiis commented on app/models/student.rb
> +      u.username = first_name
`first_name` as a user name might cause problem if we have `User.username` as a `unique` column. you might want to use `email_id` or `admission_no` or some unique combination.

2016-09-30 16:45 UTC, swapiis commented on app/views/employees/admission1.html.erb
> +
what is this extra line for?

2016-09-30 16:46 UTC, swapiis commented on app/views/layouts/_index.html.erb
> +        <%= image_tag(current_user.general_setting,class: "hidden-xs") %>
how will it show an image if you have removed the `.image` call?

2016-09-30 16:47 UTC, swapiis commented on app/views/layouts/_index.html.erb
> +  <% elsif current_user.role == 'Student' || 'Parent' %>
Please consider using the `case` statement of ruby rather than the `elsif` ladder

2016-09-30 16:48 UTC, swapiis commented on config/database.yml
>    adapter: mysql2
this file should not come in the commit. Look after the `.gitignore` file

2016-09-30 16:48 UTC, DhanshreeK commented on app/controllers/home_controller.rb
> +  prepend_before_filter :require_no_authentication, only: [:cancel ]
I found it on stackover flow as the employee were not getting added through login page i got an error so i used it.

2016-09-30 16:49 UTC, DhanshreeK commented on app/controllers/users_controller.rb
> +    @student = User.where(role: 'Student').take
okay

2016-09-30 16:50 UTC, swapnilv92 commented on db/migrate/20140906045056_create_employees.rb
> +      t.references :users
create a separate migration to update some already existing table/column. Don't ever try such hacks in migrations.

2016-09-30 16:51 UTC, swapiis commented on db/migrate/20160924063848_create_user_employees.rb
> +class CreateUserEmployees < ActiveRecord::Migration
what is the need for new table? can't we use the existing one?

2016-09-30 16:51 UTC, DhanshreeK commented on app/models/student.rb
> +      u.username = first_name
user name is not used anywhere so i prefered first_name as it was there

2016-09-30 16:52 UTC, DhanshreeK commented on app/views/layouts/_index.html.erb
> +  <% elsif current_user.role == 'Student' || 'Parent' %>
okay ill do the changes.

2016-10-01 03:41 UTC, swapnilv92 requested changes
Use proper indentations. Standard indentation for RoR is `2 spaces`. You can change setting in ST from bottom right corner. `Indent using spaces` & `2 spaces`

2016-10-03 09:35 UTC, swapiis commented on app/controllers/application_controller.rb
> +    rescue_from CanCan::AccessDenied do |_exception|
alignment is not proper

2016-10-03 09:36 UTC, swapiis commented on app/controllers/employees_controller.rb
>    # create instance for all employee departments ,call instance method emp_no
use `rubocop` to review this file

2016-10-03 09:37 UTC, swapiis commented on app/controllers/home_controller.rb
> +  prepend_before_filter :require_no_authentication, only: [:cancel ]
what does it do?
you just added because you found it on `SoF` ?

2016-10-03 09:38 UTC, swapiis commented on app/models/student.rb
> +      u.username = first_name
for now it is not getting used but we might need it in future.
Ideally it should be unique.

2016-10-03 09:39 UTC, swapiis commented on app/views/employees/admission1.html.erb
>         <span style="color:red">*</span>
Why have you added so much spaces in the code?

2016-10-05 17:31 UTC, swapiis commented on app/controllers/application_controller.rb
> +<<<<<<< HEAD
you didn't solve merge conflicts??

2016-10-05 17:32 UTC, swapiis commented on app/models/employee.rb
> +<<<<<<< HEAD
Solve conflicts & refactor this condition to a single line.

2016-10-05 17:33 UTC, swapiis commented on app/models/user.rb
> +def create_user_student(admission_no,email)
you didn't use `rubocop` properly. I am not seeing proper indentation.

2016-10-05 17:34 UTC, swapiis commented
It is still showing 12 commits?

2016-10-06 10:28 UTC, closed without merging